# Generated by Django 2.1.1 on 2019-04-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='tdesc',
            new_name='Task_Description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='tname',
            new_name='Task_Name',
        ),
    ]
